<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Eliminar Alumno';
$this->url('alumno', ['action' => 'delete', 'run' => $run]);


$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($alumno->nombre) ?>" by
    "<?= $this->escapeHtml($alumno->apellido) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $alumno->run ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>