<?php
    $title = 'Modificar Alumno';
    $this->headTitle($title);
?>
    <!--<h1><?= $this->escapeHtml($title) ?></h1>-->

<?php
    $rund = $form->get('run');
    $rund->setAttribute('class', 'form-control');
    $rund->setAttribute('placeholder', 'Run');

    $nombre = $form->get('nombre');
    $nombre->setAttribute('class', 'form-control');
    $nombre->setAttribute('placeholder', 'Nombre');

    $apellido = $form->get('apellido');
    $apellido->setAttribute('class', 'form-control');
    $apellido->setAttribute('placeholder', 'Apellido');

    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('alumno', [
        'action' => 'edit',
        'run'     => $run
    ]));
    $form->prepare();

    echo $this->form()->openTag($form);
?>

<!-- TUTORIAL

<div class="form-group">
    <?= $this->formLabel($rund) ?>
    <?= $this->formElement($rund) ?>
    <?= $this->formElementErrors()->render($rund, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($nombre) ?>
    <?= $this->formElement($nombre) ?>
    <?= $this->formElementErrors()->render($nombre, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($apellido) ?>
    <?= $this->formElement($apellido) ?>
    <?= $this->formElementErrors()->render($apellido, ['class' => 'help-block']) ?>
</div>

-->
        <div class="container mt-4 col-lg-4">
            <div class="card border-info">
                <div class="card-header bg-info">
                    <h4 class="text-center text-white">Modificar Registro</h4>
                </div>
                <div class="card-body">
                    <?= $this->formLabel($rund) ?>
                    <?= $this->formElement($rund) ?>
                    <?= $this->formElementErrors()->render($rund, ['class' => 'help-block']) ?>
                    <?= $this->formLabel($nombre) ?>
                    <?= $this->formElement($nombre) ?>
                    <?= $this->formElementErrors()->render($nombre, ['class' => 'help-block']) ?>
                    <?= $this->formLabel($apellido) ?>
                    <?= $this->formElement($apellido) ?>
                    <?= $this->formElementErrors()->render($apellido, ['class' => 'help-block']) ?>
                    <br>
                    <a class="btn btn-success col-sm-4" href="<?= $this->url('alumno') ?>"><span class="fa fa-arrow-left"></span> Volver</a>
                    <button type="submit" class="btn btn-primary col-sm-4 pull-right"><span class="fa fa-save"></span> Guardar</button>
                </div>
            </div>
        </div>

<?php
//echo $this->formSubmit($submit);
//echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();